<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Test Report</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    
<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         { }

/* -- heading ---------------------------------------------------------------------- */
h1 {
	font-size: 16pt;
	color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    padding: 10px;
    background-color: #E6E6D6;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
}
#header_row {
    font-weight: bold;
    color: white;
    background-color: #777;
}
#result_table td {
    border: 1px solid #777;
    padding: 2px;
}
#total_row  { font-weight: bold; }
.passClass  { background-color: #6c6; }
.failClass  { background-color: #c60; }
.errorClass { background-color: #c00; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

</style>

</head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class='heading'>
<h1>Test Report</h1>
<p class='attribute'><strong>Start Time:</strong> 2017-11-28 09:57:48</p>
<p class='attribute'><strong>Duration:</strong> 0:00:00.281000</p>
<p class='attribute'><strong>Status:</strong> Error 15</p>

<p class='description'>若要查看详细结果,请下载附件查看！</p>
</div>



<p id='show_detail_line'>Show
<a href='javascript:showCase(0)'>Summary</a>
<a href='javascript:showCase(1)'>Failed</a>
<a href='javascript:showCase(2)'>All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row'>
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaLogin_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c1',1)">Detail</a></td>
</tr>

<tr id='ft1.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_guanjia_login</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.1')" >
        error</a>

    <div id='div_ft1.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.1: &lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"password":"12345678","version":"1.1.0"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF3foXbKM/lLZnKHEnTgnfaFo+95g5DNLRpxJeSBbhHXZpvIVM5Em2mOV+KfZMwnvEA=
接口地址： http://t.efang100.cc/steward/common/login
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case01_guanjia_login.py", line 89, in test_guanjia_login
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/common/login?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF3foXbKM%2FlLZnKHEnTgnfaFo%2B95g5DNLRpxJeSBbhHXZpvIVM5Em2mOV%2BKfZMwnvEA%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002766B70&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaLogin_1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c2',1)">Detail</a></td>
</tr>

<tr id='ft2.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_guanjia_login</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.1')" >
        error</a>

    <div id='div_ft2.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft2.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft2.1: &lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"mobile":"182110788922","source":1,"password":"12345678","version":"1.1.0"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPegffhrL9oFmkuHAEegJZ0JtqGZr6qdlwdh4DTr6wXJYndFuu/5NXVt2LFwDThYvBRlT5YqdIL0FLzQIGsgR3rQ=
接口地址： http://t.efang100.cc/steward/common/login
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case01_guanjia_login.py", line 89, in test_guanjia_login
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/common/login?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPegffhrL9oFmkuHAEegJZ0JtqGZr6qdlwdh4DTr6wXJYndFuu%2F5NXVt2LFwDThYvBRlT5YqdIL0FLzQIGsgR3rQ%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002782710&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaLogin_2</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c3',1)">Detail</a></td>
</tr>

<tr id='ft3.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_guanjia_login</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.1')" >
        error</a>

    <div id='div_ft3.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.1: &lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"password":"1234567890","version":"1.1.0"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF3foXbKM/lLZnKHEnTgnfaFZswITdfF4qToUnDn3Xxx7EGWv3u8XQry/4I93FDif4I=
接口地址： http://t.efang100.cc/steward/common/login
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case01_guanjia_login.py", line 89, in test_guanjia_login
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/common/login?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF3foXbKM%2FlLZnKHEnTgnfaFZswITdfF4qToUnDn3Xxx7EGWv3u8XQry%2F4I93FDif4I%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002782FD0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c4',1)">Detail</a></td>
</tr>

<tr id='ft4.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.1')" >
        error</a>

    <div id='div_ft4.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.1: &lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"version":"1.1.0","type_id":"3"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF2UUit9h+dlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJunORAjGPQxo
接口地址： http://t.efang100.cc/steward/common/getSmsCode
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 95, in test_modify_pwd
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/common/getSmsCode?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF2UUit9h%2BdlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJunORAjGPQxo&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002782A58&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c5',1)">Detail</a></td>
</tr>

<tr id='ft5.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.1')" >
        error</a>

    <div id='div_ft5.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft5.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft5.1: 获取到的最新token: 56vL2jmNidNqRlXzxsgYSytX4XhVatv9
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\paramunittest.py", line 89, in setUp
    self.setParameters(*parameters[0], **parameters[1])
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 52, in setParameters
    yzm = configDB.MyDB().zhiyu_yzm(sql)
  File "D:\interfaceTest\common\configDB.py", line 87, in zhiyu_yzm
    cursor = self.executeSQL(sql)
  File "D:\interfaceTest\common\configDB.py", line 53, in executeSQL
    self.cursor.execute(sql)
AttributeError: 'NoneType' object has no attribute 'execute'


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_2</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c6',1)">Detail</a></td>
</tr>

<tr id='ft6.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.1')" >
        error</a>

    <div id='div_ft6.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft6.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft6.1: &lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"mobile":"18211078892","source":1,"version":"1.1.0","type_id":"2"}
加密后的密文： lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W+dF2UUit9h+dlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJkuQD6dNwZbk
接口地址： http://t.efang100.cc/steward/common/getSmsCode
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 95, in test_modify_pwd
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/common/getSmsCode?encrypt=DES&amp;param=lAHyQ4545oY2eyfKi2uvPUz4JRdViGgZ3gHdL8W%2BdF2UUit9h%2BdlA8CEFaqt9XaYoYzh3DkmOffvOys5CMzcJkuQD6dNwZbk&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000000281C198&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaModifyPwd_3</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c7',1)">Detail</a></td>
</tr>

<tr id='ft7.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_modify_pwd</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.1')" >
        error</a>

    <div id='div_ft7.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft7.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft7.1: 获取到的最新token: 56vL2jmNidNqRlXzxsgYSytX4XhVatv9
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\paramunittest.py", line 89, in setUp
    self.setParameters(*parameters[0], **parameters[1])
  File "D:\interfaceTest\testCase\case_guanjia_old\case03_guanjia_modifypwd.py", line 52, in setParameters
    yzm = configDB.MyDB().zhiyu_yzm(sql)
  File "D:\interfaceTest\common\configDB.py", line 87, in zhiyu_yzm
    cursor = self.executeSQL(sql)
  File "D:\interfaceTest\common\configDB.py", line 53, in executeSQL
    self.cursor.execute(sql)
AttributeError: 'NoneType' object has no attribute 'execute'


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaAccountInfo_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c8',1)">Detail</a></td>
</tr>

<tr id='ft8.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_account_info</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.1')" >
        error</a>

    <div id='div_ft8.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft8.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft8.1: 获取到的最新token: 56vL2jmNidNqRlXzxsgYSytX4XhVatv9
&lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"access_token":"56vL2jmNidNqRlXzxsgYSytX4XhVatv9","source":1,"version":"1.1.0"}
加密后的密文： PwFy53E8NrjLcKW6L7rTtmrK7iJik2Saeumtm+oMIND2CTwCLFwVevDYbGpCB0UqpVZXmdC2YDcBEcbqMlPcZRNqK4mEu7aYEaMtzuYV0+8/tn7BlHbjCw==
接口地址： http://t.efang100.cc/steward/account/info
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case04_guanjia_account_info.py", line 97, in test_account_info
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/account/info?encrypt=DES&amp;param=PwFy53E8NrjLcKW6L7rTtmrK7iJik2Saeumtm%2BoMIND2CTwCLFwVevDYbGpCB0UqpVZXmdC2YDcBEcbqMlPcZRNqK4mEu7aYEaMtzuYV0%2B8%2Ftn7BlHbjCw%3D%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000000281C1D0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaUserAvatar_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c9',1)">Detail</a></td>
</tr>

<tr id='ft9.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_user_avatar</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.1')" >
        error</a>

    <div id='div_ft9.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft9.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft9.1: 获取到的最新token: 56vL2jmNidNqRlXzxsgYSytX4XhVatv9
&lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"access_token":"56vL2jmNidNqRlXzxsgYSytX4XhVatv9","source":1,"version":"1.1.0"}
加密后的密文： PwFy53E8NrjLcKW6L7rTtmrK7iJik2Saeumtm+oMIND2CTwCLFwVevDYbGpCB0UqpVZXmdC2YDcBEcbqMlPcZRNqK4mEu7aYEaMtzuYV0+8/tn7BlHbjCw==
接口地址： http://t.efang100.cc/steward/account/avatar
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case05_guanjia_user_avatar.py", line 97, in test_user_avatar
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/account/avatar?encrypt=DES&amp;param=PwFy53E8NrjLcKW6L7rTtmrK7iJik2Saeumtm%2BoMIND2CTwCLFwVevDYbGpCB0UqpVZXmdC2YDcBEcbqMlPcZRNqK4mEu7aYEaMtzuYV0%2B8%2Ftn7BlHbjCw%3D%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000000281C748&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaSignature_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c10',1)">Detail</a></td>
</tr>

<tr id='ft10.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_signature</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft10.1')" >
        error</a>

    <div id='div_ft10.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft10.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft10.1: 获取到的最新token: 56vL2jmNidNqRlXzxsgYSytX4XhVatv9
&lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"access_token":"56vL2jmNidNqRlXzxsgYSytX4XhVatv9","source":1,"version":"1.1.0"}
加密后的密文： PwFy53E8NrjLcKW6L7rTtmrK7iJik2Saeumtm+oMIND2CTwCLFwVevDYbGpCB0UqpVZXmdC2YDcBEcbqMlPcZRNqK4mEu7aYEaMtzuYV0+8/tn7BlHbjCw==
接口地址： http://t.efang100.cc/steward/account/signature
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case06_guanjia_signature.py", line 95, in test_signature
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/account/signature?encrypt=DES&amp;param=PwFy53E8NrjLcKW6L7rTtmrK7iJik2Saeumtm%2BoMIND2CTwCLFwVevDYbGpCB0UqpVZXmdC2YDcBEcbqMlPcZRNqK4mEu7aYEaMtzuYV0%2B8%2Ftn7BlHbjCw%3D%3D&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000000281CC18&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaVersionUpdate_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c11',1)">Detail</a></td>
</tr>

<tr id='ft11.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_version_update</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.1')" >
        error</a>

    <div id='div_ft11.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft11.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft11.1: 读取的data {u'source': 1, u'version': u'1.1.0', u'site_id': 1}
&lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"source":1,"version":"1.1.0","site_id":1}
加密后的密文： PawnCmfK+rKCBXE0KrEHFv7eFm3ZJgSk6TgAsQb7Cg/OlnNf8J23db4Pn9lrM+yc
接口地址： http://t.efang100.cc/steward/account/version
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case07_guanjia_version_update.py", line 98, in test_version_update
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/account/version?encrypt=DES&amp;param=PawnCmfK%2BrKCBXE0KrEHFv7eFm3ZJgSk6TgAsQb7Cg%2FOlnNf8J23db4Pn9lrM%2Byc&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002824160&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaAddClient_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c12',1)">Detail</a></td>
</tr>

<tr id='ft12.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_add_client</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.1')" >
        error</a>

    <div id='div_ft12.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft12.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft12.1: 获取到的最新token: 56vL2jmNidNqRlXzxsgYSytX4XhVatv9
&lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"name":"\u5218\u5c0f\u826f","access_token":"56vL2jmNidNqRlXzxsgYSytX4XhVatv9","user_pwd":"12345678","sex":"1","source":1,"customer_type":"1","version":"1.1.0","mobile":"18211078892","account_status":"1","card_no":"370481198811156472"}
加密后的密文： Q2xE9kr0PBLZkk7GV+h+spNrLjt/51OVyabpk2gJ175qvh87rFZxdUdBqRfFGV46a3JZwMv7SOC/bdhejPNiXGZC33U6MxPim9gOCj8/L69guIk1LXdN923ZBH4kppeCtTPgWyj/Q5VyZDQEuSZoSkCyRaSGA4k8WkQlGvb+byN21KeNwmjpuf3kjcWGNpAWVx4Ef5yARM57RTSAKLyQsItBsCGDVaEWd1qkImRnaA1c7RaJy+X7X79zbZa1AzdHAQNT/D1ZiDKxBxqxWdhesMYhRgnoWjBt6tUSqU+2MOJE1EPUw+LSsQXbnNDAA68x
接口地址： http://t.efang100.cc/steward/user/add
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case08_guanjia_add_client.py", line 94, in test_add_client
    self.response = localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp.py", line 81, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/user/add?encrypt=DES&amp;param=Q2xE9kr0PBLZkk7GV%2Bh%2BspNrLjt%2F51OVyabpk2gJ175qvh87rFZxdUdBqRfFGV46a3JZwMv7SOC%2FbdhejPNiXGZC33U6MxPim9gOCj8%2FL69guIk1LXdN923ZBH4kppeCtTPgWyj%2FQ5VyZDQEuSZoSkCyRaSGA4k8WkQlGvb%2BbyN21KeNwmjpuf3kjcWGNpAWVx4Ef5yARM57RTSAKLyQsItBsCGDVaEWd1qkImRnaA1c7RaJy%2BX7X79zbZa1AzdHAQNT%2FD1ZiDKxBxqxWdhesMYhRgnoWjBt6tUSqU%2B2MOJE1EPUw%2BLSsQXbnNDAA68x&amp;client_id=1fobqa5ofzixluyjlum7icdufabjfo25 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002824630&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaAddClient_1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c13',1)">Detail</a></td>
</tr>

<tr id='ft13.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_add_client</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft13.1')" >
        error</a>

    <div id='div_ft13.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft13.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft13.1: 获取到的最新token: 56vL2jmNidNqRlXzxsgYSytX4XhVatv9
&lt;type 'dict'&gt;
字典转成json
&lt;type 'str'&gt;
将json格式params去掉空格、换行:  {"org_code_type":"1","legal_name":"\u5218\u6631\u826f","name":"\u5218\u5c0f\u826f","access_token":"56vL2jmNidNqRlXzxsgYSytX4XhVatv9","company_name":"\u4e00\u623f","user_pwd":"12345678","sex":"1","source":1,"customer_type":"1","version":"1.1.0","mobile":"18211078892","account_status":"1","credit_code":"1","card_no":"370481198811156472"}
加密后的密文： Go0Ns+M+TK82lu6gqA064xlXaUbT4Z7UBF4BI920Td7EShAqKoLoWH+H5anmABg/G/qYuqjZzhbe+s+TqIAJjJLnGev6+5e7l7g0Lcj1vG5G3Srqzf3cQS6Ysf5M8CO5iQlOQCG70XOL9YxAOBzlGxyXmIPK1Gd/Bpc8AHnbdxmwYU8P3AysGOZubNwCVDJDILNQjGnB2MNnhBsY1CwwgoNl/E3X2rXKqA2SCEvuHYzlpwqY7mmruPbz83p7hLv5JiuwA4PwGXlB83EUWOgEi0a5uIpLl1LMmT6rBTTm7DF2Ht9cl0Lz+g/UpOgyLMiffh4Srs2TnVMOSy5jI3a+w6pkz7yBV5Vd26SyeC2C0cyAUMdSqEZqqGQBIzAkalXiOKKbxIjc7FuUHOfzfz6FSUdY2bH4uy60lggHT9InCRVwZkn6q9IRrWcclCpXYvMtqcz5S/uGE0Q=
接口地址： http://t.efang100.cc/steward/user/add
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_old\case08_guanjia_add_client.py", line 97, in test_add_client
    self.response = localConfigHttp.post()
  File "D:\interfaceTest\common\configHttp.py", line 98, in post
    response = requests.post(self.url, headers=self.headers, data=self.params, timeout=float(timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.efang100.cc', port=80): Max retries exceeded with url: /steward/user/add (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002824AC8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaSignHomepage_0</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c14',1)">Detail</a></td>
</tr>

<tr id='ft14.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sign_homepage</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft14.1')" >
        error</a>

    <div id='div_ft14.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft14.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft14.1: 完整接口地址： http://t.api.efang100.cc/rent/sign/index
加密key为:  ia1Yh85O26LARD8M
加密iv为:  1234567890123456
加密模式为:  2
{"source": 1, "version": "1.1.0", "site_id": 1, "house_id": "1635064", "timestamp": 1511834268}
&lt;type 'str'&gt;
将json格式params去空格、换行:  {"source":1,"version":"1.1.0","site_id":1,"house_id":"1635064","timestamp":1511834268}
加密后字符串为:  YHlct7FL+r0oGSHoddfAqn4ZXmwlDB6VkV7hN2N6m+hRniAES1ue5TCnkgbogUzr4UXjJscwxWgrvuOEWk62syQVGcPDRE0GkrXEn9TB/RfJy4KacgrUwqeQfudsua+y
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_new\case09_guanjia_sign_homepage.py", line 107, in test_sign_homepage
    self.response = self.localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp_new.py", line 83, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(self.timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.api.efang100.cc', port=80): Max retries exceeded with url: /rent/sign/index?param=YHlct7FL%2Br0oGSHoddfAqn4ZXmwlDB6VkV7hN2N6m%2BhRniAES1ue5TCnkgbogUzr4UXjJscwxWgrvuOEWk62syQVGcPDRE0GkrXEn9TB%2FRfJy4KacgrUwqeQfudsua%2By (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002824C88&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr class='errorClass'>
    <td>paramunittest.GuanJiaSignHomepage_1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c15',1)">Detail</a></td>
</tr>

<tr id='ft15.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sign_homepage</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft15.1')" >
        error</a>

    <div id='div_ft15.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft15.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft15.1: 完整接口地址： http://t.api.efang100.cc/rent/sign/index
加密key为:  ia1Yh85O26LARD8M
加密iv为:  1234567890123456
加密模式为:  2
{"source": 1, "version": "1.1.0", "site_id": 1, "house_id": "16350640", "timestamp": 1511834268}
&lt;type 'str'&gt;
将json格式params去空格、换行:  {"source":1,"version":"1.1.0","site_id":1,"house_id":"16350640","timestamp":1511834268}
加密后字符串为:  YHlct7FL+r0oGSHoddfAqn4ZXmwlDB6VkV7hN2N6m+hRniAES1ue5TCnkgbogUzrZBZw2f0F87cQXxHpiXccePUP39NQKxVDLfYyGEXIaXNf5SNR5igufm/925gxgySv
Traceback (most recent call last):
  File "D:\interfaceTest\testCase\case_guanjia_new\case09_guanjia_sign_homepage.py", line 107, in test_sign_homepage
    self.response = self.localConfigHttp.get()
  File "D:\interfaceTest\common\configHttp_new.py", line 83, in get
    response = requests.get(self.url, headers=self.headers, params=self.params, timeout=float(self.timeout))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='t.api.efang100.cc', port=80): Max retries exceeded with url: /rent/sign/index?param=YHlct7FL%2Br0oGSHoddfAqn4ZXmwlDB6VkV7hN2N6m%2BhRniAES1ue5TCnkgbogUzrZBZw2f0F87cQXxHpiXccePUP39NQKxVDLfYyGEXIaXNf5SNR5igufm%2F925gxgySv (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000000282E7B8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>15</td>
    <td>0</td>
    <td>0</td>
    <td>15</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

</body>
</html>
